import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Frontend Developer",
    company: "PT Bits Miliartha",
    link: "https://www.linkedin.com/company/beeid",
    logo: "https://res.cloudinary.com/dqhjsjrqc/image/upload/v1729691249/Personal/Beecloud_logo_guhvdj.png",
    location: "Sidoarjo",
    type: "Fulltime",
    start_date: "2023-12",
    end_date: null,
  },
  {
    position: "Frontend Developer",
    company: "PT Blackwolf Indonesia",
    link: "https://www.linkedin.com/company/blackwolftech",
    logo: "https://res.cloudinary.com/dqhjsjrqc/image/upload/v1693691029/Personal/blackwolftech.png",
    location: "Remote",
    type: "Freelance",
    start_date: "2022-12",
    end_date: null,
  },
  {
    position: "UI/UX Design Manager",
    company: "Career Network",
    link: "https://www.linkedin.com/company/career-network-id/",
    logo: "https://res.cloudinary.com/dqhjsjrqc/image/upload/v1693691029/Personal/careernetwork.png",
    location: "Remote",
    type: "Internship",
    start_date: "2022-06",
    end_date: "2022-09",
  },
  {
    position: "Laboratory Assistant",
    company: "FILKOM UB",
    link: "https://www.linkedin.com/company/filkombrawijaya/",
    logo: "https://res.cloudinary.com/dqhjsjrqc/image/upload/v1693691029/Personal/filkomub.png",
    location: "Malang",
    type: "Part Time",
    start_date: "2022-02",
    end_date: "2022-07",
  },
  {
    position: "UI/UX Designer",
    company: "Skilvul",
    link: "https://www.linkedin.com/company/skilvul/    ",
    logo: "https://res.cloudinary.com/dqhjsjrqc/image/upload/v1693691029/Personal/skilvul.png",
    location: "Remote",
    type: "Internship",
    start_date: "2021-08",
    end_date: "2021-12",
  },
];
